### ISSUE TITLE
Create a resource fails with cloudwatch:PutMetricData error

### ISSUE THREAD

**Issue by jeshan** [aws-cloudformation/cloudformation-cli-go-plugin#109] opened 2019-12-29 14:01 UTC
I've created and registered my first resource provider but I cannot create resources out of it.
I'm seeing this in cfn and cloudwatch logs:

```
2019/12/29 11:32:19 Handler returned  OperationStatus: FAILED Message: Unable to complete request: ServiceInternal: Publisher error
caused by: ServiceInternal: Publisher error
caused by: AccessDenied: User: arn:aws:sts::607306539146:assumed-role/uluru-managed-execution-role/bb53badc-a2e5-df40-6809-0d6682b6a031 is not authorized to perform: cloudwatch:PutMetricData
	status code: 403, request id: b51ca0a1-b387-4c65-beb9-1cb56722ebc4 CallbackContext: map[] Delay: 0, ErrorCode: GENERALSERVICEEXCEPTION  
```

The handler code is fairly bare bone and I've even explicitly added the said permission to in my schema (redacted handler):
```golang
func Create(req handler.Request, prevModel *Model, currentModel *Model) (handler.ProgressEvent, error) {
    // Add your code here:
    // * Make API calls (use req.Session)
    // * Mutate the model
    // * Check/set any callback context (req.CallbackContext / response.CallbackContext)

    // Construct a new handler.ProgressEvent and return it
    response := handler.ProgressEvent{
        OperationStatus: handler.Success,
        Message: "Create complete",
        ResourceModel: currentModel,
    }

    return response, nil
}
```

I saw this cfn template got deployed via `cfn submit -v` in the stack `***-role-stack`:
![image](https://user-images.githubusercontent.com/1020565/71557753-f47a3500-2a63-11ea-9c28-a3b4b521ea48.png)

In the stack named `CloudFormationManagedUploadInfrastructure`, I see that the execution role has the following policy:
![image](https://user-images.githubusercontent.com/1020565/71557748-d3b1df80-2a63-11ea-9130-a6a2504fe40c.png)
Shouldn't that have been enough?

What's missing to fix this IAM issue?

**Comment by jeshan** [comment] 2020-01-05 16:54
@jotompki I tried the above with very simple operations. Did custom providers ever work with the go plugin?

**Comment by rjlohan** [comment] 2020-01-06 15:39
> @jotompki I tried the above with very simple operations. Did custom providers ever work with the go plugin?

Yes we have a few setup but some changes to the backend may have introduced this failing condition related to metrics. Is the issue still present on the latest codebase?

**Comment by jeshan** [comment] 2020-01-06 16:36
ok RJ,
Not sure if I understood your question correctly; when I wrote that I tried the above, I was referring to my own code; not the PR #108 mentioned. I'm waiting for the PR to get merged to retry.

**Comment by rjlohan** [comment] 2020-01-06 16:46
#108 is merged so can you create a new version of your resource and republish to see if the issue is resolved?

**Comment by jeshan** [comment] 2020-01-06 19:20
Looks much better, thanks. Should I close it or should it be tested in a proper release first?

**Comment by rjlohan** [comment] 2020-01-06 22:16
I think we're good to close this now.

**Closed by rjlohan** 2020-01-06 22:16 UTC

**Comment by pennywisdom** [comment] 2020-01-07 07:51
Hi, I have been getting this issue or similar, I just retried after pushing my resource again but am still receiving the same issue with my resource type in eu-west-2. Do i need to update the plugin on my system or is this fix all at the backend?
Thanks

**Comment by jeshan** [comment] 2020-01-07 09:35
you need to update the plugin on your side to depend on "master"

**Comment by pennywisdom** [comment] 2020-01-07 09:43
Thanks @jeshan
