### ISSUE TITLE
AWS Credentials in provider expire during provider's lifetime

### ISSUE THREAD

**Issue by pawelaugustyn** [aws-cloudformation/cloudformation-cli-go-plugin#155] opened 2020-08-25 13:36 UTC
After migrating code to the latest release with protocol version 2.0.0, I started experiencing intermittent errors when provider's handler is supposed to reach out to AWS APIs using its credentials.

Code used to call AWS APIs:

```go
func findConfiguration(session *session.Session) (*ProviderConfiguration, error) {
        if ssmClient == nil {
                ssmClient = ssm.New(session, aws.NewConfig().WithRegion("us-east-1"))
        }
        config, err := getParameter(ssmClient, ConfigKey)
        if err != nil {
                return nil, fmt.Errorf("cannot read default provider config: %w", err)
        }

        var cf ProviderConfiguration
        err = json.Unmarshal([]byte(config), &cf)
        if err != nil {
                return nil, fmt.Errorf("failed to unmarshal config JSON string: %w", err)
        }
        return &cf, nil
}

func getParameter(s ssmiface.SSMAPI, parameter string) (string, error) {
        param, err := s.GetParameter(&ssm.GetParameterInput{
                Name:           a.String(parameter),
                WithDecryption: a.Bool(false),
        })
        if err != nil {
                return "", fmt.Errorf("failed to retrieve parameter %s: %w", parameter, err)
        }
        return a.StringValue(param.Parameter.Value), nil
}
```

Stack failure reason: `Unable to retrieve Name attribute for Org::Test::Record`
Resource failure reason: `cannot read default provider config: failed to retrieve parameter <removed>: ExpiredTokenException: The security token included in the request is expired`

Observed issue is quite hard to replicate as it occurs intermittently. The only thing I can say is that's the first time we've observed such issue for last few months.

Providing role, partial resource schema and rpdk-config as an attachments. In both files and attached snippets I've removed business-specific vocabulary.
[role.txt](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/files/5124016/role.txt)
[schema.txt](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/files/5123969/schema.txt)
[rpdk-config.txt](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/files/5123949/rpdk-config.txt)

**Comment by brianterry** [comment] 2020-08-26 14:38
Hi @pawelaugustyn , thank you for submitting this issue. Is this error returned when trying to stabilize the resource (returning a callbackcontext and in_progress event)?

**Comment by pawelaugustyn** [comment] 2020-08-27 15:31
Hey @brianterry,
Yeah, we do use callbackcontext to provide polling mechanism.
What I think is that error is returned after resource's update is finished. I see in my service's log that provider initiated one PATCH request (to initialize update) and then produced one GET request which returned information that update process is completed.
Error may suggest that after resource update has been finished, CloudFormation tried to perform another READ on the resource to obtain output value (I use `Name` property as one of CFN outputs in the stack) and this is the moment when credentials unexpectedly expired.

**Comment by omkhegde** [comment] 2020-09-02 16:09
Thanks @pawelaugustyn. Can you please test whether the issue is still reproducible after the recent bug fixes?

**Comment by pawelaugustyn** [comment] 2020-09-02 18:56
Currently we've updated cloudformation-cli-go-plugin module to specific commit version (`c1261e85f57d527c71d9f5a5a4a96018a442fffa`) and we haven't noticed that kind of issue.

**Comment by omkhegde** [comment] 2020-09-18 20:13
This issue seems to be fixed with @brianterry 's fix for log throttle. Closing the issue.

**Closed** 2020-09-18 20:13 UTC
