### ISSUE TITLE
Internal Failure when invoking handler with protocol version 2.0.0

### ISSUE THREAD

**Issue by gbernady** [aws-cloudformation/cloudformation-cli-go-plugin#153] opened 2020-08-18 12:19 UTC
After migrating code to the latest release with protocol version 2.0.0, I started experiencing `Internal Failure` errors when provider's handler is supposed to be called by the CloudFormation service.

There's no stack trace, panic or any other log message in CloudWatch, including those printed by the cloudformation-cli-go-plugin itself like `Initialization of log stream`. To me it looks like either the handler is not invoked at all or it crashes very early before invoking any of my code.

I reproduce this easily with a sample provider I attached here: [sample_project.zip](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/files/5090216/sample_project.zip). The CloudFormation template I used is:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Resources:
  Inst0:
    Type: 'Foo::Bar::Resource'
  Inst1:
    Type: 'Foo::Bar::Resource'
  Inst2:
    Type: 'Foo::Bar::Resource'
  Inst3:
    Type: 'Foo::Bar::Resource'
  Inst4:
    Type: 'Foo::Bar::Resource'
  Inst5:
    Type: 'Foo::Bar::Resource'
  Inst6:
    Type: 'Foo::Bar::Resource'
  Inst7:
    Type: 'Foo::Bar::Resource'
  Inst8:
    Type: 'Foo::Bar::Resource'
  Inst9:
    Type: 'Foo::Bar::Resource'
```

In one of my attempts ([stack_events.log](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/files/5090278/stack_events.log)), resource `Inst5` suddenly failed with "Internal Failure" message, which triggered a rollback where `Inst3` failed to delete with "Internal Failure". This case is very interesting, because the implementation of the `Delete` function cannot panic or fail for any reason as it just logs the request it received and returns a SUCCESS:

```go
// Delete handles the Delete event from the Cloudformation service.
func Delete(req handler.Request, prevModel *Model, currentModel *Model) (handler.ProgressEvent, error) {
	log.Printf("DELETE called, req: %+v", req)
	return handler.ProgressEvent{OperationStatus: handler.Success, ResourceModel: currentModel}, nil
}
```

PS. In the sample project I'm using my fork of cloudformation-cli-go-plugin with #149 applied (https://github.com/gbernady/cloudformation-cli-go-plugin/commit/63252b66e78f436552e8223428356685f56624c6). I made no other changes to the codebase.

**Comment by wbingli** [comment] 2020-08-19 16:06
@gbernady Thanks for reporting this issue. We are looking at it.

**Comment by wbingli** [comment] 2020-08-20 07:47
We can reproduce this issue. It happens when there are multiple resources making request to the handler at the same time. We are still looking into root cause.

**Comment by brianterry** [comment] 2020-08-31 14:27
@gbernady, Thanks for reporting this. We just merged a fix. The issue was caused by CloudWatch Log throttling. A lot of  resources launch within a short time caused CloudWatch Logs to throttling API calls. Therefore caused the timeout of the call's context to be exceeded. The fix reduces the call the CloudWatch.

**Closed** 2020-09-01 13:42 UTC
